/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_uninstall_browser_sdk_UninstallBrowserSDK */

#ifndef _Included_com_uninstall_browser_sdk_UninstallBrowserSDK
#define _Included_com_uninstall_browser_sdk_UninstallBrowserSDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_uninstall_browser_sdk_UninstallBrowserSDK
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL
        Java_com_netease_nr_base_activity_UnInstallMonitor_init(JNIEnv *, jclass, jstring, jstring,jint);
JNIEXPORT jint JNICALL
        Java_com_netease_nr_base_activity_UnInstallMonitor_initByPoll(JNIEnv *, jclass, jstring, jstring,jint);

#ifdef __cplusplus
}
#endif
#endif
